// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5229.DeepSpaceCompetitionBot;

import org.usfirst.frc5229.DeepSpaceCompetitionBot.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Joystick.AxisType;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.buttons.POVButton;
import edu.wpi.first.wpilibj.buttons.Trigger;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton halfSpeedControl;
    public JoystickButton quarterSpeedControl;
    public JoystickButton deployClimber;
    public JoystickButton retractClimber;
    public JoystickButton climbWheelDriveOn;
    public JoystickButton climbWheelDriveOff;
    public Joystick driveController;
    public JoystickButton inputBallBtn;
    public JoystickButton outputBallBtn;
    public JoystickButton removeElevatorLimitsBtn;
    public JoystickButton raiseElevatorMidball;
    public JoystickButton raiseElevatorHighball;
    public JoystickButton lowerElevator;
    public JoystickButton raiseElevatorLowball;
    public JoystickButton raiseelevatorHatchDelivery;
    public Joystick mechanismController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public POVButton POVUp;
    public POVButton POVLeft;
    public POVButton POVRight;
    public POVButton POVDown;

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        mechanismController = new Joystick(1);
        
        raiseelevatorHatchDelivery = new JoystickButton(mechanismController, 8);
        raiseelevatorHatchDelivery.whileHeld(new ElevatorCmd());
        raiseElevatorLowball = new JoystickButton(mechanismController, 1);
        raiseElevatorLowball.whileHeld(new ElevatorCmd());
        lowerElevator = new JoystickButton(mechanismController, 3);
        lowerElevator.whileHeld(new ElevatorCmd());
        raiseElevatorHighball = new JoystickButton(mechanismController, 4);
        raiseElevatorHighball.whileHeld(new ElevatorCmd());
        raiseElevatorMidball = new JoystickButton(mechanismController, 2);
        raiseElevatorMidball.whileHeld(new ElevatorCmd());
        removeElevatorLimitsBtn = new JoystickButton(mechanismController, 7);
        removeElevatorLimitsBtn.whileHeld(new ElevatorCmd());
        outputBallBtn = new JoystickButton(mechanismController, 5);
        outputBallBtn.whileHeld(new RollerCmd());
        inputBallBtn = new JoystickButton(mechanismController, 6);
        inputBallBtn.whileHeld(new RollerCmd());
        driveController = new Joystick(0);
        
        climbWheelDriveOff = new JoystickButton(driveController, 4);
        climbWheelDriveOff.whileHeld(new ClimbCmd());
        climbWheelDriveOn = new JoystickButton(driveController, 3);
        climbWheelDriveOn.whileHeld(new ClimbCmd());
        retractClimber = new JoystickButton(driveController, 2);
        retractClimber.whileHeld(new ClimbCmd());
        deployClimber = new JoystickButton(driveController, 1);
        deployClimber.whileHeld(new ClimbCmd());
        quarterSpeedControl = new JoystickButton(driveController, 5);
        quarterSpeedControl.whileHeld(new DrivetrainCmd());
        halfSpeedControl = new JoystickButton(driveController, 6);
        halfSpeedControl.whileHeld(new DrivetrainCmd());


        // SmartDashboard Buttons

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    SmartDashboard.putNumber("Elevator Position", Robot.elevatorSub.pos);
        POVUp = new POVButton(mechanismController, 0);
        POVLeft = new POVButton(mechanismController, 270);
        POVRight = new POVButton(mechanismController, 90);
        POVDown = new POVButton(mechanismController, 180);
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriveController() {
        return driveController;
    }

    public Joystick getMechanismController() {
        return mechanismController;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

