// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5229.DeepSpaceCompetitionBot.commands;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5229.DeepSpaceCompetitionBot.Robot;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Joystick.AxisType;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.buttons.POVButton;
import edu.wpi.first.wpilibj.buttons.Trigger;

/**
 *
 */
public class AutonomousCommand extends Command { 
    public JoystickButton halfSpeedControl;
    public JoystickButton quarterSpeedControl;
    public JoystickButton joystickButton1;
    public Joystick driveController;
    public JoystickButton inputBallBtn;
    public JoystickButton outputBallBtn;
    public JoystickButton removeElevatorLimitsBtn;
    public Joystick mechanismController;
    public POVButton POVUp;
    public POVButton POVLeft;
    public POVButton POVRight;
    public POVButton POVDown; 

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousCommand() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrainSub);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        
        driveController = new Joystick(0);
        
        Robot.drivetrainSub.drive(Robot.oi.driveController.getRawAxis(0), -Robot.oi.driveController.getRawAxis(1), Robot.oi.driveController.getRawAxis(4));    

        joystickButton1 = new JoystickButton(driveController, 1);
        joystickButton1.whileHeld(new AutoAlignCmd());
        quarterSpeedControl = new JoystickButton(driveController, 5);
        halfSpeedControl = new JoystickButton(driveController, 6);
               

        mechanismController = new Joystick(1);

        
        removeElevatorLimitsBtn = new JoystickButton(mechanismController, 1);
        outputBallBtn = new JoystickButton(mechanismController, 3);
        inputBallBtn = new JoystickButton(mechanismController, 2);

        POVUp = new POVButton(mechanismController, 0);
        POVLeft = new POVButton(mechanismController, 270);
        POVRight = new POVButton(mechanismController, 90);
        POVDown = new POVButton(mechanismController, 180);

        
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
