// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5229.DeepSpaceCompetitionBot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5229.DeepSpaceCompetitionBot.Robot;

/**
 *
 */
public class DrivetrainCmd extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    public double contDeadZone = 0.01;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DrivetrainCmd() {
        requires(Robot.drivetrainSub);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrainSub);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if (Robot.oi.driveController.getRawButton(5) == false && Robot.oi.driveController.getRawButton(6) == false) {
            if (Robot.oi.driveController.getRawAxis(0) < -contDeadZone || -Robot.oi.driveController.getRawAxis(1) < -contDeadZone || Robot.oi.driveController.getRawAxis(4) < -contDeadZone || Robot.oi.driveController.getRawAxis(0) > contDeadZone || -Robot.oi.driveController.getRawAxis(1) > contDeadZone || Robot.oi.driveController.getRawAxis(4) > contDeadZone) {
                Robot.drivetrainSub.drive(Robot.oi.driveController.getRawAxis(0) * .75, -Robot.oi.driveController.getRawAxis(1) * .75, Robot.oi.driveController.getRawAxis(4) * .75);    
            }
            else {
                Robot.drivetrainSub.drive(0, 0, 0);
            }
        }
        else if (Robot.oi.driveController.getRawButton(5) == true && Robot.oi.driveController.getRawButton(6) == true) {
            if (Robot.oi.driveController.getRawAxis(0) < -contDeadZone || -Robot.oi.driveController.getRawAxis(1) < -contDeadZone || Robot.oi.driveController.getRawAxis(4) < -contDeadZone || Robot.oi.driveController.getRawAxis(0) > contDeadZone || -Robot.oi.driveController.getRawAxis(1) > contDeadZone || Robot.oi.driveController.getRawAxis(4) > contDeadZone) {
                Robot.drivetrainSub.drive(Robot.oi.driveController.getRawAxis(0), -Robot.oi.driveController.getRawAxis(1), Robot.oi.driveController.getRawAxis(4));    
            }
            else {
                Robot.drivetrainSub.drive(0, 0, 0);
            }
        }
        else if (Robot.oi.driveController.getRawButton(5) == true && Robot.oi.driveController.getRawButton(6) == false) {
            if (Robot.oi.driveController.getRawAxis(0) < -contDeadZone || -Robot.oi.driveController.getRawAxis(1) < -contDeadZone || Robot.oi.driveController.getRawAxis(4) < -contDeadZone || Robot.oi.driveController.getRawAxis(0) > contDeadZone || -Robot.oi.driveController.getRawAxis(1) > contDeadZone || Robot.oi.driveController.getRawAxis(4) > contDeadZone) {
                Robot.drivetrainSub.drive(Robot.oi.driveController.getRawAxis(0) / 4, -Robot.oi.driveController.getRawAxis(1) / 4, Robot.oi.driveController.getRawAxis(4) / 4);    
            }
            else {
                Robot.drivetrainSub.drive(0, 0, 0);
            }
        }
        else if (Robot.oi.driveController.getRawButton(5) == false && Robot.oi.driveController.getRawButton(6) == true) {
            if (Robot.oi.driveController.getRawAxis(0) < -contDeadZone || -Robot.oi.driveController.getRawAxis(1) < -contDeadZone || Robot.oi.driveController.getRawAxis(4) < -contDeadZone || Robot.oi.driveController.getRawAxis(0) > contDeadZone || -Robot.oi.driveController.getRawAxis(1) > contDeadZone || Robot.oi.driveController.getRawAxis(4) > contDeadZone) {
                Robot.drivetrainSub.drive(Robot.oi.driveController.getRawAxis(0) / 2, -Robot.oi.driveController.getRawAxis(1) / 2, Robot.oi.driveController.getRawAxis(4) / 2);    
            }
            else {
                Robot.drivetrainSub.drive(0, 0, 0);
            }
        }
        
        
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
